#
# TABLE STRUCTURE FOR: NEWS
#

DROP TABLE IF EXISTS `NEWS`;

CREATE TABLE `NEWS` (
  `datapacket_id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `admission_type_code` varchar(20) NOT NULL,
  `admission_source_code` varchar(20) NOT NULL,
  `admission_category_code` varchar(20) NOT NULL,
  `referrer_code` varchar(25) NOT NULL,
  `discharge_date` date NOT NULL,
  `discharge_ward_code` varchar(25) NOT NULL,
  `discharge_consultant_code` varchar(25) NOT NULL,
  `discharge_method_code` varchar(25) NOT NULL,
  `discharge_destination_code` varchar(25) NOT NULL,
  `sex` varchar(1) NOT NULL,
  `site_code` varchar(25) NOT NULL,
  `ward_code` varchar(25) NOT NULL,
  `bay_code` varchar(5) NOT NULL,
  `bay_name` varchar(50) NOT NULL,
  `bed_number` varchar(25) NOT NULL,
  `admission_date` date NOT NULL,
  `time_of_reading` date NOT NULL,
  `packet_type_code` int(11) unsigned NOT NULL,
  `packet_type` varchar(25) NOT NULL,
  `ews_score` int(11) unsigned NOT NULL,
  `ews_level_code` int(11) unsigned NOT NULL,
  `ews_level` varchar(8) NOT NULL,
  `ews_incomplete` varchar(1) NOT NULL,
  `ews_incomplete_max` int(11) unsigned NOT NULL,
  `pulse` varchar(255) NOT NULL,
  `pulse_value` int(11) unsigned NOT NULL,
  `temp` varchar(50) NOT NULL,
  `temp_value` varchar(50) NOT NULL,
  `bp_sys` varchar(50) NOT NULL,
  `bp_sys_value` int(11) unsigned NOT NULL,
  `bp_dia` varchar(50) NOT NULL,
  `bp_dia_value` int(9) unsigned NOT NULL,
  `resp_rate` varchar(50) NOT NULL,
  `resp_rate_value` int(11) unsigned NOT NULL,
  `avpu` varchar(50) NOT NULL,
  `o2_sats` varchar(50) NOT NULL,
  `o2_sats_value` varchar(50) NOT NULL,
  `mask_type` varchar(50) NOT NULL,
  `o2_flowrate` varchar(50) NOT NULL,
  `ow_conc` varchar(50) NOT NULL,
  `pain_score` varchar(50) NOT NULL,
  `pain_score_value` int(11) unsigned NOT NULL,
  `nausea` varchar(50) NOT NULL,
  `vomiting` varchar(50) NOT NULL,
  `bowels` varchar(50) NOT NULL,
  `bowels_value` varchar(50) NOT NULL,
  `height` varchar(50) NOT NULL,
  `painheight_value_score` varchar(50) NOT NULL,
  `weight` varchar(50) NOT NULL,
  `weight_value` varchar(50) NOT NULL,
  `time_started_obs` varchar(50) NOT NULL,
  `time_submitted` varchar(50) NOT NULL,
  PRIMARY KEY (`datapacket_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE NEWS AUTO_INCREMENT = 0